$(VERBOSE).SILENT:

all:
	echo "Please run \"make ex_XX\" where XX is a number from 0 to 5"

ex_00:
	javac ex00/Program.java
	java ex00.Program ex00.Temp

ex_01:
	javac ex01/Program.java
	java ex01.Program

ex_02:
	javac ex02/Program.java
	java ex02.Program

ex_03:
	javac ex03/Program.java
	java ex03.Program

ex_04:
	javac ex04/Program.java
	java ex04.Program

ex_05:
	javac ex05/Program.java
	java ex05.Program $(arg)

clean:
	rm **/*.class
